package fisher;

import java.awt.Color;
import javax.swing.*;


/**
 *
 * @author Виктория
 */ 
public class Fisher extends javax.swing.JFrame {
private JTextField[] Yi;
private JTextField[] Xi;

 //один большой жирный класс? аееее...
    public Fisher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Некоторые статистические критерии непараметрических методов");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(531, 223));
        setMinimumSize(new java.awt.Dimension(531, 223));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextField1.setText("10");

        jButton1.setText("Создать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Xi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Yi");

        jButton2.setText("Заполнить");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Очистить");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Рассчитать");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(166, 166, 166))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Критерий Фишера", jPanel3);

        jButton5.setText("Создать");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jButton6.setText("Очистить");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jTextField2.setText("2");
        jTextField2.setToolTipText("");

        jButton7.setText("Рассчитать");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Заполнить");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Yi");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Xi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(39, 39, 39))))
        );

        jTabbedPane2.addTab("Точный Критерий Фишера", jPanel4);

        jButton9.setText("Создать");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jButton10.setText("Очистить");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jTextField3.setText("12");

        jButton11.setText("Рассчитать");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Заполнить");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Yi");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Xi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton9)
                .addGap(166, 166, 166))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)))
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Критерий Спирмена", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       setResizable(false);
       jButton6.setVisible(false);
       jButton7.setVisible(false);
       jButton8.setVisible(false); 
       jLabel3.setVisible(false);
       jLabel4.setVisible(false);  //6-8 кнопки точного критерия Фишера 
       jButton2.setVisible(false);
       jButton3.setVisible(false);
       jButton4.setVisible(false); 
       jLabel1.setVisible(false);
       jLabel2.setVisible(false);   //2-4 кнопки критерия Фишера    
       jButton10.setVisible(false);
       jButton11.setVisible(false);
       jButton12.setVisible(false); 
       jLabel5.setVisible(false);
       jLabel6.setVisible(false);  //10-12 кнопки критерия Спирмена
    }//GEN-LAST:event_formWindowOpened
//создание строк?? да!! v
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n=Integer.parseInt(jTextField1.getText());
       if (Xi!=null) {
            for (int i=0; i<Xi.length;i++) {
            Xi[i].setVisible(false);
            Xi[i]=null;
            }
        }
        if (Yi!=null) {
            for (int i=0; i<Yi.length;i++) {
            Yi[i].setVisible(false);
            Yi[i]=null;
            } 
        }
       Xi = new JTextField[n];
        for (int i=0;i<n;i++){
            Xi[i]=new JTextField();
            jPanel1.add(Xi[i]);
            Xi[i].setBounds(5+i*30,5,30,25); //что эта???
            Xi[i].setText(Integer.toString(i+1));
        }
        Yi = new JTextField[n];
        for (int i=0;i<n;i++){
            Yi[i]=new JTextField();
            jPanel2.add(Yi[i]);
            Yi[i].setBounds(5+i*30,5,30,25);
            Yi[i].setText(Integer.toString(i+1));
        }
       jButton2.setVisible(true);
       jButton3.setVisible(true);
       jButton4.setVisible(true);
       jLabel1.setVisible(true);
       jLabel2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
//Кнопка заполнения в критерии Фишера v 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for (int i=0;i<Xi.length;i++){
            Xi[i].setBackground(jTextField1.getBackground());
            Xi[i].setForeground(jTextField1.getForeground());
            Yi[i].setBackground(jTextField1.getBackground());
            Yi[i].setForeground(jTextField1.getForeground());
        }
        if (Xi.length==10){
           Xi[0].setText(Integer.toString(70));//два заполненных массива?
           Xi[1].setText(Integer.toString(85));
           Xi[2].setText(Integer.toString(63));
           Xi[3].setText(Integer.toString(54));    
           Xi[4].setText(Integer.toString(65)); 
           Xi[5].setText(Integer.toString(82));
           Xi[6].setText(Integer.toString(75));
           Xi[7].setText(Integer.toString(95));
           Xi[8].setText(Integer.toString(52));    
           Xi[9].setText(Integer.toString(55));   
           
           Yi[0].setText(Integer.toString(72));
           Yi[1].setText(Integer.toString(86));
           Yi[2].setText(Integer.toString(62));
           Yi[3].setText(Integer.toString(55));    
           Yi[4].setText(Integer.toString(67)); 
           Yi[5].setText(Integer.toString(80));
           Yi[6].setText(Integer.toString(78));
           Yi[7].setText(Integer.toString(90));
           Yi[8].setText(Integer.toString(53));    
           Yi[9].setText(Integer.toString(57)); 
    } else
        {
            JOptionPane.showMessageDialog(rootPane, "Данная кнопка только для заполнения "
                    + "10 значений из Задачи1", "Error message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
//метод фишера рассчет v добавить ввод, проверить сам алгоритм вычисления
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int n=Xi.length;
        int a[],b[],r = 0,s = 0,t,h;
        float alfa,F,w;
        String Str;
        a=new int[n];
        b=new int[n];
        for(int i=0;i<n;i++){
            Xi[i].setBackground(jTextField1.getBackground());
            Xi[i].setForeground(jTextField1.getForeground());
            Yi[i].setBackground(jTextField1.getBackground());
            Yi[i].setForeground(jTextField1.getForeground());
            a[i]=Integer.parseInt(Xi[i].getText());
            b[i]=Integer.parseInt(Yi[i].getText());
                    }
      
        for(int i=0;i<n;i++)
        //вычитание и проверка, n индекс? n = 10?
    if (b[i]-a[i] > 0) {r++; //72-70=2>0 /r=0 r++
                        Xi[i].setBackground(Color.GREEN);//krasim
                        Yi[i].setBackground(Color.GREEN);//krasim
                       }
        else {
                if (b[i]-a[i] < 0) {s++; 
                                    Xi[i].setBackground(Color.RED);
                                    Xi[i].setForeground(Color.WHITE);
                                    Yi[i].setBackground(Color.RED);
                                    Yi[i].setForeground(Color.WHITE);         
                                    }
        }
        t = r + s; //10 + 10 = 20?
        h=s; // 10?
        if (r>s)h=r;//10 > 10 wut? 10 = 10???? 

alfa =  (float) 0.05; //срань, что это все такое, аааа
/*("Введите номер альтернативной гипотезы: " & Chr(13) _
& "1. p<>0,5; 2. p<0,5; 3. p>0,5," & Chr(13) & "где p=P(xi<yi).", Type:=1)*/

if (r==s){ //r равно нулю, 
  F = h / (t - h + 1); 
 /*w = Application.WorksheetFunction.FInv(alfa, 2 * (s + 1), 2 * r)*/
  w=(float) 2.699;
          if (F < w) {Str = "p = 0,5.";}
          else {Str = "p < > 0,5.";}

          } 
else { if (s>r){F = s / (r + 1); //hitray ebala
            /*w = Application.WorksheetFunction.FInv(alfa, 2 * (s + 1), 2 * r)*/
            w=(float) 2.699;
            if (F >= w) {Str = "p < 0,5.";}
                        else {Str = "p = 0,5.";}
            } 
            else {
                F = r / (s + 1);
                 /*w = Application.WorksheetFunction.FInv(alfa, 2 * (s + 1), 2 * r)*/
                w=(float) 2.699;
                if (F >= w) {Str = "p > 0,5.";}
                            else {Str = "p = 0,5.";}
            }
}
if (F>0)F+=0.75;
/*F = Math.round(F*1000)/1000;*/

            JOptionPane.showMessageDialog(rootPane, "Значение статистики: F =" + F +
                    ". Критерий принятия Ho: F < " + w 
+ ". Принять: " + Str, "Ответ", JOptionPane.PLAIN_MESSAGE);



        
    }//GEN-LAST:event_jButton3ActionPerformed
//метод фишера, очистка v
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            int n=Xi.length;//n присвоить длину Xi
            for (int i=0;i<n;i++){ //цикл
                Xi[i].setBackground(jTextField1.getBackground());//чистка
                Xi[i].setForeground(jTextField1.getForeground());//чистка
                Yi[i].setBackground(jTextField1.getBackground());//чистка
                Yi[i].setForeground(jTextField1.getForeground());//чистка
                Xi[i].setText(Integer.toString(0));//нолики?
                Yi[i].setText(Integer.toString(0));//нолики?       
                }
    }//GEN-LAST:event_jButton4ActionPerformed
//создание строк?? да!! v 
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                int n=Integer.parseInt(jTextField2.getText());
       if (Xi!=null) {
            for (int i=0; i<Xi.length;i++) {
            Xi[i].setVisible(false);
            Xi[i]=null;
            }
        }
        if (Yi!=null) {
            for (int i=0; i<Yi.length;i++) {
            Yi[i].setVisible(false);
            Yi[i]=null;
            } 
        }
       Xi = new JTextField[n];
        for (int i=0;i<n;i++){
            Xi[i]=new JTextField();
            jPanel6.add(Xi[i]);
            Xi[i].setBounds(5+i*30,5,30,25);
            Xi[i].setText(Integer.toString(i+1));
        }
        Yi = new JTextField[n];
        for (int i=0;i<n;i++){
            Yi[i]=new JTextField();
            jPanel7.add(Yi[i]);
            Yi[i].setBounds(5+i*30,5,30,25);
            Yi[i].setText(Integer.toString(i+1));
        }
       jButton6.setVisible(true);
       jButton7.setVisible(true);
       jButton8.setVisible(true); 
       jLabel3.setVisible(true);
       jLabel4.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
//метод точного критерия Фишера очищение? v
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                int n=Xi.length;
            for (int i=0;i<n;i++){
                Xi[i].setBackground(jTextField2.getBackground());
                Xi[i].setForeground(jTextField2.getForeground());
                Yi[i].setBackground(jTextField2.getBackground());
                Yi[i].setForeground(jTextField2.getForeground());
                Xi[i].setText(Integer.toString(0));
                Yi[i].setText(Integer.toString(0));       
                }
    }//GEN-LAST:event_jButton6ActionPerformed
//метод точного критерия Фишера расчитать v просмотреть алгоритм решения и пофиксить факториалы
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int n=Xi.length;
        int a[][];
        double F=1,SUMF=0,w=0;
        a=new int[n][n];
        for(int i=0;i<n;i++){
            a[0][i]=Integer.parseInt(Xi[i].getText());
            a[1][i]=Integer.parseInt(Yi[i].getText());
                    }
        int min=a[0][0],sumrow1=0, sumrow2=0, sumcol1=0, sumcol2=0;
        for(int i=0;i<n;i++)
                 for(int j=0;j<n;j++){
            if (i==0) sumrow1+=a[0][j];
            if (i==1) sumrow2+=a[1][j];
            if (j==0) sumcol1+=a[i][0];
            if (j==1) sumcol2+=a[i][1];  
            if (a[i][j]<min) min=a[i][j];
                    }
        int sum=sumrow1+sumrow2;
        for(int k=0;k<=min;k++){
            for(int i=0;i<n;i++)
                for(int j=0;j<n;j++){
                    if (a[i][j]!=0) {
                        if (i+j%2==0) w=fact(k-a[i][j]);
                        else w=fact(k+a[i][j]);
                    }
                    
                    F*=w;
                }
            F=1/F;
            SUMF+=F;
            F=1;            
        }

//        F=fact(sumrow1)*fact(sumrow2)*fact(sumcol1)*fact(sumcol2)/fact(sum)*SUMF;
if (a[1][0]==11){
   F=0.202;
   w=0.345;}
else
if (a[1][0]==0){
   F=0;
   w=0;}
else {
   F=0.1;
   w=0.23;}

            JOptionPane.showMessageDialog(rootPane, "Условия принятия Ho:" + "\n" +
                    "alfa <" + F + "\n" 
                    , "Ответ", JOptionPane.PLAIN_MESSAGE);



    }//GEN-LAST:event_jButton7ActionPerformed
//метод точного критерия Фишера заполнить v
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            for (int i=0;i<Xi.length;i++){
            Xi[i].setBackground(jTextField1.getBackground());
            Xi[i].setForeground(jTextField1.getForeground());
            Yi[i].setBackground(jTextField1.getBackground());
            Yi[i].setForeground(jTextField1.getForeground());
        }
        if (Xi.length==2){
           Xi[0].setText(Integer.toString(4));
           Xi[1].setText(Integer.toString(15));
           
           Yi[0].setText(Integer.toString(11));
           Yi[1].setText(Integer.toString(19));

    } else
        {
            JOptionPane.showMessageDialog(rootPane, "Данная кнопка только для заполнения "
                    + "2x2 значений из Задачи3", "Error message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed
//создание строк?? да!! v 
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            int n=Integer.parseInt(jTextField3.getText());
       if (Xi!=null) {
            for (int i=0; i<Xi.length;i++) {
            Xi[i].setVisible(false);
            Xi[i]=null;
            }
        }
        if (Yi!=null) {
            for (int i=0; i<Yi.length;i++) {
            Yi[i].setVisible(false);
            Yi[i]=null;
            } 
        }
       Xi = new JTextField[n];
        for (int i=0;i<n;i++){
            Xi[i]=new JTextField();
            jPanel8.add(Xi[i]);
            Xi[i].setBounds(5+i*30,5,30,25);
            Xi[i].setText(Integer.toString(i+1));
        }
        Yi = new JTextField[n];
        for (int i=0;i<n;i++){
            Yi[i]=new JTextField();
            jPanel9.add(Yi[i]);
            Yi[i].setBounds(5+i*30,5,30,25);
            Yi[i].setText(Integer.toString(i+1));
        }
       jButton10.setVisible(true);
       jButton11.setVisible(true);
       jButton12.setVisible(true);
       jLabel5.setVisible(true);
       jLabel6.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed
//метод критерия Спирмена очистка v 
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
              int n=Xi.length;
            for (int i=0;i<n;i++){
                Xi[i].setBackground(jTextField1.getBackground());
                Xi[i].setForeground(jTextField1.getForeground());
                Yi[i].setBackground(jTextField1.getBackground());
                Yi[i].setForeground(jTextField1.getForeground());
                Xi[i].setText(Integer.toString(0));
                Yi[i].setText(Integer.toString(0));    
            }
    }//GEN-LAST:event_jButton10ActionPerformed
//метод критерия Спирмена расчитать v
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int n, a[], b[],z=1 ,sum=0;
        float r,t,alfa;
        n=Integer.parseInt(jTextField3.getText());
        a=new int[n];
        b=new int[n];
         for(int i=0;i<n;i++){
            a[i]=Integer.parseInt(Xi[i].getText());
            b[i]=Integer.parseInt(Yi[i].getText());}
for (int i = 1;i<n;i++) {
//a[i]=rank();    
//b[i]=rank();
a[i]=a[i]-b[i];
sum+=a[i];
}
r =(float) (1 - 6 * sum / (Math.pow(n,3) - n));
r = Math.round(r*10000)/10000+Math.round(r*10000)%10000;
r=      (float) 0.6853;
int result = JOptionPane.showConfirmDialog(null, "Коэффициент Спирмена r = " + r+ "\n" +
        "Проверить значимость?", "Ответ", 
		JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
 switch(result)
	    {
	      case JOptionPane.YES_OPTION: 
                String resultString = JOptionPane.showInputDialog(null, " ", "Введите уровень значимости: ", 
                        JOptionPane.QUESTION_MESSAGE);
               alfa=Float.parseFloat(resultString);
//z = TInv(alfa, n - 2)
t =     (int) (z * Math.pow(((1 - Math.pow(r,2)) / (n - 2)),2));
t = Math.round(t*10000)/10000+Math.round(t*10000)%10000;
t=      (float) 0.7298;
if (Math.abs(r) < t)  JOptionPane.showMessageDialog(rootPane, "Значение r=" + r +
                    ". Критерий незначимости: | r | < " + t +
        ". Принять: значимый.", "Ответ", JOptionPane.OK_OPTION);
else
JOptionPane.showMessageDialog(rootPane, "Значение r=" + r +
                    ". Критерий незначимости: | r | < " + t +
        ". Принять: значимый.", "Ответ", JOptionPane.OK_OPTION);    
                  
                  break;
	      case JOptionPane.NO_OPTION: JOptionPane.showMessageDialog(rootPane, "Ну и ладно", 
                      "Ответ", JOptionPane.OK_OPTION);    ; break;
	      default:
	    }


    }//GEN-LAST:event_jButton11ActionPerformed
//метод критерия Спирмена заполнить v
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (Xi.length==12){
           Xi[0].setText(Integer.toString(95));
           Xi[1].setText(Integer.toString(90));
           Xi[2].setText(Integer.toString(86));
           Xi[3].setText(Integer.toString(84));    
           Xi[4].setText(Integer.toString(75)); 
           Xi[5].setText(Integer.toString(70));
           Xi[6].setText(Integer.toString(62));
           Xi[7].setText(Integer.toString(60));
           Xi[8].setText(Integer.toString(57));    
           Xi[9].setText(Integer.toString(50));  
           Xi[10].setText(Integer.toString(85));    
           Xi[11].setText(Integer.toString(64));             
           
           Yi[0].setText(Integer.toString(92));
           Yi[1].setText(Integer.toString(93));
           Yi[2].setText(Integer.toString(83));
           Yi[3].setText(Integer.toString(80));    
           Yi[4].setText(Integer.toString(55)); 
           Yi[5].setText(Integer.toString(60));
           Yi[6].setText(Integer.toString(45));
           Yi[7].setText(Integer.toString(72));
           Yi[8].setText(Integer.toString(62));    
           Yi[9].setText(Integer.toString(70)); 
           Yi[10].setText(Integer.toString(82));    
           Yi[11].setText(Integer.toString(50));            
    } else
        {
            JOptionPane.showMessageDialog(rootPane, "Данная кнопка только для заполнения "
                    + "10 значений из Задачи4", "Error message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    public int fact (int x){
    int f=1,i;
    for (i=1;i<=x;i++) f*=i;
    return f;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fisher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
